# Generated by Django 3.2.9 on 2021-12-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0006_remove_post_user'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
