# Generated by Django 3.2.9 on 2021-12-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0005_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
