# Generated by Django 3.2.9 on 2021-12-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_menuitem_menu_app_me_menu_id_a0f054_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='menu_app.menu'),
        ),
    ]
